# Generated by Django 4.2.1 on 2023-06-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
